---

- hosts: koffan_group
  remote_user: root
  tasks:
    - name: Ensure koffan folder exists
      ansible.builtin.file:
        path: "{{ KOFFAN_DATA_PATH }}"
        state: directory
        mode: "0750"

    - name: Ensure proxy network exists
      ansible.builtin.include_tasks: ../tasks/ensure-proxy-network.yml

    - name: Copy configuration templates
      ansible.builtin.template:
        src: "compose.yml"
        dest: "{{ KOFFAN_DATA_PATH }}/compose.yml"
        owner: root
        group: root
        mode: "0644"

    - name: Start koffan stack
      community.docker.docker_compose_v2:
        project_name: koffan
        project_src: "{{ KOFFAN_DATA_PATH }}"
        state: present

    - name: Notify completion
      ansible.builtin.include_tasks: ../tasks/notify-ntfy.yml
      vars:
        notify_service: "Koffan"
