  [nextcloud]
  type = webdav
  url = https://{{ NEXTCLOUD_DOMAIN }}/remote.php/dav/files/{{ NEXTCLOUD_ADMIN_USERNAME }}/
  vendor = nextcloud
  user = {{ NEXTCLOUD_ADMIN_USERNAME }}
  pass = {{ NEXTCLOUD_RCLONE_TOKEN }}